### ISSUE TITLE
Problem on docker image update

### ISSUE THREAD

**Issue by loewyn** [ddkhanh/bookstack-pdf-viewer#1]
Hello,

Everything works perfectly, just a problem with the lifecycle of this method. There was an update this weekend of the Docker image, and it overwrote the files and NGINX configuration. Do you have any idea how we could proceed to avoid any issues in the future? This time, I followed the procedure again, and everything is back to normal, but having the container on automatic update is not ideal!

Thank you very much.

**Comment by ddkhanh** [comment]
Hello,

it is easy to achieve, you can follow with the below steps: 

### Step 1: Update docker-compose file to mount pdfjs for bookstack container

![image](https://github.com/ddkhanh/bookstack-pdf-viewer/assets/5151868/5403f84b-ab40-4b6d-8a30-6ccdaf67a9c7)

Then copy everything inside pdfjs file to the mounted folder 

```bash
cp * pdfjs/* <your mounted folder>/pdfjs
```

### Step 2:  Update nginx config file 

For the javascript mine types, it can be achieved by modifying the nginx config file which is stored in bookstack's volume
Append these lines to the nginx.conf file

```js
 types {
                application/javascript  mjs;
        }
```

![image](https://github.com/ddkhanh/bookstack-pdf-viewer/assets/5151868/cfec7783-a851-4a7e-83c1-ed48cc823c37)

For example, mine setup: 
```bash
vi ./bookstack_app_data/nginx/nginx.conf
```

Then restart all bookstack containers
```bash
docker-compose restart
```

Thanks,
Khanh

**Comment by loewyn** [comment]
Hello,

Simple but effective. I hadn't really taken the time to think about it, and I would certainly have had difficulties with the NGINX part, which differs from the method in the Readme.

Now, everything is working normally. I restarted the stack by re-downloading the images to ensure that Docker completely overwrites any configuration that might have been done directly in the container, and it worked right away.

I think it would be better to update the Readme so that this procedure is integrated for anyone who wants to use a PDF reader.

Thank you very much!

**Comment by ddkhanh** [comment]
Hello @loewyn , thank you for the feedback. I have updated the Readme
