### ISSUE TITLE
Sizing the pdf integration

### ISSUE THREAD

**Issue by Harimzial** [ddkhanh/bookstack-pdf-viewer#2]
Hi,

First of all, thanks a lot for this resources, we are currently implementing this for our employee documentation and they really wanted a better pdf management. 
This answers it more than perfectly and I could follow the installation as well as the update you made a few hours ago.

But I come across an issue which may not be fully related : 
- When adding a pdf, the size is very small and I cannot really change that (see screenshots).
- If I try to extend it a lot, it grows more of large then of lengths and goes out of the border of the page
<img width="647" alt="image" src="https://github.com/ddkhanh/bookstack-pdf-viewer/assets/148787649/08061ff7-155a-44b1-adf3-4f04f02193fe">
<img width="647" alt="image" src="https://github.com/ddkhanh/bookstack-pdf-viewer/assets/148787649/b6fb26c3-bf48-4ee4-9bdb-2ef8a0615fd5">
<img width="647" alt="image" src="https://github.com/ddkhanh/bookstack-pdf-viewer/assets/148787649/643e483d-43cf-47e1-96f5-96d2cf290fb3">

I might just be dumb on this one, and I first looked at pdf.js support but it doesn't seem to help. Maybe you have any hints ?

Also another question and again I'm sorry it might be out of this project. But any modification done to the pdf trough pdf.js is local to each user right ?

Thanks a lot again!
Best regards.

**Comment by ddkhanh** [comment]
Hi @Harimzial , I'm glad that this guideline helped. Regarding the height, I have updated the default setup per your setting.

> Also another question and again I'm sorry it might be out of this project. But any modification done to the pdf trough pdf.js is local to each user right ?


Since it is not persisted, it does not affect the PDF source file, and thus other users.
