### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by biziosan** [ddkhanh/bookstack-pdf-viewer#3]
Hi,

Thank you so much for your solution! I really appreciated it. I have a problem, though. No matter what I insert in the PDF URL field, I always get a "Page Not Found" message. I am using v24.05.

**Comment by ddkhanh** [comment]
Hello @biziosan ,
I haven't tried with external PDF URL so I'm not sure if you entered external URL to the PDF ULR field.
And. did you try with the attachment? Upload a PDF file to your page and the copy the link to that file. Thanks

**Comment by biziosan** [comment]
Hi @ddkhanh,

Thank you for your help with this issue! 

Yes, that is the very first thing I tried. BTW, the link downloads correctly if copied and pasted in a browser. If I add `?open=true` to the URL, the attachments open directly in the browser tab. My Bookstack installation is brand new. I have not changed the upload size limits yet, but the test file is only 400KB. I am currently using the `STORAGE_TYPE=local_secure_restricted` setting for the attachments.

This is from the dev log window with some of the attempts:
```
GET https://archai:6875/pdfjs/web/viewer.html?file=https://archai:6875/attachments/1 404 (Not Found)
GET https://archai:6875/pdfjs/web/viewer.html?file=https://archai:6875/attachments/1?open=true 404 (Not Found)
GET https://archai:6875/pdfjs/web/viewer.html?file=attachments/1 404 (Not Found)
GET https://archai:6875/pdfjs/web/viewer.html?file=attachments/1 404 (Not Found)
GET https://archai:6875/pdfjs/web/viewer.html?file=/attachments/1 404 (Not Found)
GET https://archai:6875/pdfjs/web/viewer.html?file=/attachments/1 404 (Not Found)
GET https://archai:6875/pdfjs/web/viewer.html?file=archai:6875/attachments/1 404 (Not Found)
GET https://archai:6875/pdfjs/web/viewer.html?file=1 404 (Not Found)
```

Of course, the first two URLs work just fine in a browser.

**Comment by ddkhanh** [comment]
Hello @biziosan ,
It seem that you do not have a correct setup with pdfjs which cause the 404 resource not found.
Open a new tab and try to view this page in your browser
https://archai:6875/pdfjs/web/viewer.html

**Comment by biziosan** [comment]
Thank you for the clue! The permissions for the pdfjs directory were not right. I changed them to 755, and everything worked. Would you consider adding this step to your guide?

**Comment by biziosan** [comment]
Thank you for the clue! The permissions for the pdfjs directory were not right. I changed them to 755, and everything worked. Would you consider adding this step to your guide?

**Comment by ddkhanh** [comment]
Hello @biziosan , Sure, I will add your findings to the setup steps. Thank you for sharing.

**Comment by biziosan** [comment]
Thank you for your guide! It was incredibly helpful to have every step in one place. Let's hope that Bookstack will include this feature permanently.
